# -*- coding: utf-8 -*-
"""DistilGPT Fine Tuning-Retail & E-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neOn-ztq1qq9Y6O689rkpZ_ON6TEqDMi
"""

!pip install -q streamlit transformers datasets pyngrok accelerate

from datasets import load_dataset

dataset = load_dataset("amazon_polarity")

print(dataset)
print(dataset["train"][0])

train_data = []

for item in dataset["train"].select(range(500)):

    review = item["content"]   # correct for amazon_polarity
    label = item["label"]

    if label == 1:
        response = "Thanks for your positive review! We are happy you liked the product."
    else:
        response = "We are sorry for your experience. We will improve our service."

    train_data.append({
        "text": f"User: {review}\nAssistant: {response}"
    })

print(train_data[0])

import json

with open("dataset.json", "w") as f:
    json.dump(train_data, f)

print("Dataset ready ✔")

from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments
from datasets import load_dataset

model_name = "distilgpt2"

dataset = load_dataset("json", data_files="dataset.json")

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

#  FIX: add labels (THIS WAS MISSING)
def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

    tokens["labels"] = tokens["input_ids"].copy()   #  IMPORTANT FIX
    return tokens

tokenized = dataset.map(tokenize)

model = AutoModelForCausalLM.from_pretrained(model_name)

training_args = TrainingArguments(
    output_dir="./shopbot_model",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    logging_steps=10,
    save_steps=50,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"]
)

trainer.train()

model.save_pretrained("./shopbot_model")
tokenizer.save_pretrained("./shopbot_model")

print("Training completed ✔")

!pip install gradio -q
!pip install transformers -q

import gradio as gr
from transformers import pipeline

# lightweight model (safe for Colab)
pipe = pipeline("text-generation", model="distilgpt2")

def chat(user_input):
    output = pipe(user_input, max_new_tokens=80)
    return output[0]["generated_text"]

ui = gr.Interface(
    fn=chat,
    inputs=gr.Textbox(label="Ask your question"),
    outputs=gr.Textbox(label="ShopBot Response"),
    title="🛍️ Retail & E-commerce AI Chatbot"
)

ui.launch(share=True)